'use strict'

try{
//x = 10
mifuncion();
}
catch(error){
    console.log(error);
}

console.log( 'continuamos...');